name: Contracts
on:
  pull_request:
    paths:
      - '**'
      - '.github/workflows/contracts.yml'
  push:
    branches:
      - main
    paths:
      - '**'
      - '.github/workflows/contracts.yml'

jobs:
  lint-and-test:
    environment: testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting
        working-directory: .
        run: forge fmt --check src/ test/ examples/

      - name: Install dependencies
        working-directory: .
        run: forge install

      - name: Check contract sizes
        working-directory: .
        run: forge build --sizes --build-info

      - name: Run Slither
        uses: crytic/slither-action@main
        id: slither
        with:
          target: ''
          slither-config: 'slither.config.json'
          fail-on: none
          ignore-compile: true

      - name: Run Solhint
        working-directory: .
        run: npx solhint 'src/**/*.sol' 'test/**/*.sol' 'examples/**/*.sol' 'script/**/*.sol' --config .solhint.json

      # - name: Check gas snapshots
      #   working-directory: .
      #   run: forge snapshot --check

      - name: Check test coverage
        working-directory: .
        run: MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} forge coverage

      - name: Run tests
        working-directory: .
        run: MAINNET_RPC_URL=${{ secrets.MAINNET_RPC_URL }} forge test
        env:
          # Only fuzz intensely if we're running this action on a push to main or for a PR going into main:
          FOUNDRY_PROFILE: ${{ (github.ref == 'refs/heads/main' || github.base_ref == 'main') && 'intense' }}
